<!-- Css Styles -->
<link rel="stylesheet" href="{{asset('dist-front/css/bootstrap.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/font-awesome.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/elegant-icons.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/flaticon.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/owl.carousel.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/nice-select.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/jquery-ui.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/magnific-popup.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/slicknav.min.css')}}" type="text/css">
<link rel="stylesheet" href="{{asset('dist-front/css/style.css')}}" type="text/css">